dateModified: 1718332400
email:
  fromEmail: olets@olets.dev
  fromName: astro-craftcms
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0bda1c6b-607d-4b82-8274-4bdc4f5a2a78: astro-craftcms # astro-craftcms
    31cbaa90-6504-4e89-87f0-d8c2ed3f5f32: 'Example Channel' # Example Channel
    83a107ea-357d-4836-b525-14319446f05c: 'Public Schema' # Public Schema
    95ef0b64-7fa5-4a78-96c8-54053c025f38: 'Example Channel Entry Type' # Example Channel Entry Type
    863cff4f-f659-488d-9614-5d2b915a50ee: astro-craftcms # astro-craftcms
    b34ffb6b-3496-4a01-a7b4-92e89cc74117: 'Example Structure' # Example Structure
    e028dd6d-44ee-41f5-b575-4921ba562311: 'Example Single Entry Type' # Example Single Entry Type
    f527f66e-862e-4c16-8439-cdb3e1f894c3: 'Example Single' # Example Single
    fb3e2e8c-14ef-4f19-90b3-64d37d6ea29f: 'Example Structure Entry Type' # Example Structure Entry Type
system:
  edition: solo
  live: true
  name: astro-craftcms
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
